apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.name }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
    {{- with .Values.configMap.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- range $k, $v := .Values.configMap.data }}
  {{ $k | quote }}: {{ $v | quote }}
  {{- end }}
