apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "oidc-gateway.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  # Currently limited to one replica due to using NGINX local cache
  replicas: 1
  selector:
    matchLabels:
      {{- include "oidc-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oidc-gateway.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config.yaml
              subPath: config.yaml
              name: config
            {{- if .Values.externalSecrets.enabled }}
            - mountPath: /app/secrets.yaml
              subPath: secrets.yaml
              name: secrets
            {{- end }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.configMap.name }}
        {{- if .Values.externalSecrets.enabled }}
        - name: secrets
          secret:
            secretName: {{ .Values.externalSecrets.name }}
        {{- end }}
