{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
  {{- with .Values.externalSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "oidc-gateway.labels" . | nindent 4 }}
    {{- with .Values.externalSecrets.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  data:
    - remoteRef:
        key: /{{ .Values.externalSecrets.secretPath }}/oidc-gateway-secrets
      secretKey: secrets.yaml
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.store }}
  target:
    name: {{ .Values.externalSecrets.target }} 
    template:
      metadata:
        {{- with .Values.externalSecrets.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        labels:
          {{- include "oidc-gateway.labels" . | nindent 10 }}
          {{- with .Values.externalSecrets.labels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
