autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
# # stage
#   minReplicas: 1
#   maxReplicas: 3
#   targetCPUUtilizationPercentage: 80
# # prod
#   minReplicas: 3
#   maxReplicas: 15
#   targetCPUUtilizationPercentage: 75

cert-manager:
  install: false

configMap:
  annotations: {}
  data:
    DISCOURSE_DB_PORT: 5432
    DISCOURSE_DB_SOCKET: ""
    DISCOURSE_DEVELOPER_EMAILS: 'it-sre@mozilla.com'
    LANG: en_US.UTF-8
    RAILS_ENV: production
    RUBY_GC_HEAP_GROWTH_MAX_SLOTS: 40000
    RUBY_GC_HEAP_INIT_SLOTS: 400000
    RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR: 1.5
    RUBY_GLOBAL_METHOD_CACHE_SIZE: 131072
    UNICORN_SIDEKIQS: 1
    UNICORN_WORKERS: 1
  labels: {}
  name: discourse

db:
  migrate:
    enabled: false
  init:
    enabled: false

deployment:
  annotations: {}
  labels: {}
  name: discourse
  replicaCount: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi

externalSecrets:
  annotations: {}
  enabled: false
  labels: {}
  loggerSecretKey: ""
  # /{env}/discourse/logger
  # AWS Secret Manager value (JSON object is 1 AWS SSM value) looks like:
  # {
  #   "files": [
  #     "/logs/rails/*.log"
  #   ],
  #   "destination": {
  #     "host": "logs.papertrailapp.com",
  #     "port": 123456,
  #     "protocol": "tls"
  #   }
  # }
  name: discourse
  # Values.externalSecrets.secrets are for external-secrets key, name, properties
  # For local environments, don't enabled externalSecrets & use the configMap block
  secrets: []
  # - key: /{env}/discourse/envvar
  #   name: DISCOURSE_AKISMET_API_KEY
  #   property: DISCOURSE_AKISMET_API_KEY
  # - key: /{env}/discourse/envvar
  #   name: DISCOURSE_AUTH0_CLIENT_ID
  #   property: DISCOURSE_AUTH0_CLIENT_ID
  # - key: /{env}/discourse/envvar
  #   name: DISCOURSE_AUTH0_CLIENT_SECRET
  #   property: DISCOURSE_AUTH0_CLIENT_SECRET
  # - key: /{env}/discourse/envvar
  #   name: DISCOURSE_DB_HOST
  #   property: DISCOURSE_DB_HOST
  # - key: /{env}/discourse/envvar
  #   name: DISCOURSE_DB_NAME
  #   property: DISCOURSE_DB_NAME
  # - key: /{env}/discourse/envvar
  #   name: DISCOURSE_DB_PASSWORD
  #   property: DISCOURSE_DB_PASSWORD
  # - key: /{env}/discourse/envvar
  #   name: DISCOURSE_DB_USERNAME
  #   property: DISCOURSE_DB_USERNAME
  # - key: /{env}/discourse/envvar
  #   name: DISCOURSE_REDIS_HOST
  #   property: DISCOURSE_REDIS_HOST
  # - key: /{env}/discourse/envvar
  #   name: DISCOURSE_S3_UPLOAD_BUCKET
  #   property: DISCOURSE_S3_UPLOAD_BUCKET
  # - key: /{env}/discourse/envvar
  #   name: DISCOURSE_SMTP_PASSWORD
  #   property: DISCOURSE_SMTP_PASSWORD
  # - key: /{env}/discourse/envvar
  #   name: DISCOURSE_SMTP_USER_NAME
  #   property: DISCOURSE_SMTP_USER_NAME

image:
  repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/discourse
  tag: dev-f58ded6-1605645320

imagePullSecrets: []

ingress:
  className: "nginx"
  hosts:
    - host: discourse-dev.allizom.org
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: discourse
          servicePort: 80
    - host: discourse.dev.mozit.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: discourse
          servicePort: 80
    # # stage
    # - host: discourse.allizom.org
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
    #       serviceName: discourse
    #       servicePort: 80
    # - host: discourse.stage.mozit.cloud
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
    #       serviceName: discourse
    #       servicePort: 80
    # # prod
    # - host: discourse.mozilla.org
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
    #       serviceName: discourse
    #       servicePort: 80
    # - host: discourse.prod.mozit.cloud
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
    #       serviceName: discourse
    #       servicePort: 80
  labels: {}
  le:
    create: false
    issuer_create: true
    name: stage
    prod: https://acme-v02.api.letsencrypt.org/directory
    stage: https://acme-staging-v02.api.letsencrypt.org/directory
  name: discourse
  tls:
    - hosts:
        - discourse-dev.allizom.org
      secretName: chart-discourse-dev-allizom-org
    - hosts:
        - discourse.dev.mozit.cloud
      secretName: chart-discourse-dev-mozit-cloud
    # # stage
    # - hosts:
    #     - discourse.allizom.org
    #   secretName: chart-discourse-allizom-org
    # - hosts:
    #     - discourse.stage.mozit.cloud
    #   secretName: chart-discourse-stage-mozit-cloud
    # # prod
    # - hosts:
    #     - discourse.mozilla.org
    #   secretName: chart-discourse-mozilla-org
    # - hosts:
    #     - discourse.prod.mozit.cloud
    #   secretName: chart-discourse-prod-mozit-cloud

metrics:
  enabled: false
  resources: {}
