apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "securitywiki.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "securitywiki.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: "25%"
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "securitywiki.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/bash"
            - "-c"
            - "chown www-data:www-data /data/securitywiki && find /data/securitywiki \\! -user www-data -exec chown -R www-data:www-data {} \\;"
          resources:
            requests:
              memory: 128Mi
              cpu: "128m"
            limits:
              memory: 128Mi
              cpu: "128m"
          volumeMounts:
            - name: securitywiki-fs
              mountPath: /data/securitywiki
      containers:
        - name: {{ .Values.deployment.name }}
          envFrom:
            - configMapRef:
                name: {{ .Values.deployment.name }}
          {{- if .Values.externalSecrets.enabled }}
            - secretRef:
                name: {{ .Values.deployment.name }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.healthchecks.path }}
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            successThreshold: 3
            httpGet:
              path: {{ .Values.deployment.healthchecks.path }}
              port: http
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: securitywiki-fs
              mountPath: /data/securitywiki
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.volume.create }}
        - name: securitywiki-fs
          persistentVolumeClaim:
            claimName: securitywiki-shared
      {{- else }}
        - name: securitywiki-fs
          emptyDir: {}
      {{- end }}
