{{- if .Values.volume.create }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.name }}
  {{- with .Values.volume.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "securitywiki.labels" . | nindent 4 }}
    {{- with .Values.volume.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.volume.accessModes }}
  capacity:
    storage: {{ .Values.volume.capacityStorage }}
  persistentVolumeReclaimPolicy: "Retain"
  nfs:
    path: "/"
    server: {{ .Values.volume.nfsServer }}
  storageClassName: {{ .Values.volume.storageClassName }}
{{- end }}
