apiVersion: v1
kind: Service
metadata:
  name: {{ include "careers.fullname" . }}
  labels:
    {{- include "careers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: web
    {{- include "careers.selectorLabels" . | nindent 4 }}
