apiVersion: v2
description: A Helm chart for OIDC Gateway workload to put in front of workloads that require an authentication layer.
name: oidc-gateway
version: 1.0.0

keywords:
  - Mozilla
  - oidc

sources:
  - https://github.com/mozilla-services/oidc-gateway

maintainers:
  - name: Web SRE Team
    email: it-sre@mozilla.com
