affinity: {}

configMap:
  annotations: {}
  data:
    oidc:
      client_id: sample_client_id
      # client_secret: secret_value_if_not_using_externalSecrets
      discovery: 'https://auth.mozilla.auth0.com/.well-known/openid-configuration'
    # session_secret: secret_value_if_not_using_externalSecrets
    upstream: upstream-svc  # populated by service behind the oidc-gateway
  labels: {}
  name: oidc-gateway

deployment:
  annotations: {}
  labels: {}
  name: oidc-gateway
  replicaCount: 1
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

externalSecrets:
  annotations: {}
  enabled: false
  secretPath: 'dev/upstream-app'  # populated by service behind the oidc-gateway
  labels: {}
  name: oidc-gateway
  # structure: { "oidc": { "client_secret": "secret key for oidc client"}, "session_secret": "oidc session secret" }

image:
  pullPolicy: IfNotPresent
  repository: mozilla/oidc-gateway
  tag: latest

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  enabled: false
  hosts:
    - chart-example.local
  path: /
  tls:
    - hosts:
        - chart-example.local
      secretName: chart-example-tls

nodeSelector: {}

service:
  type: ClusterIP
  port: 80

tolerations: []
