apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
  {{- with .Values.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    {{- with .Values.configMap.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- range $k, $v := .Values.configMap.data }}
  {{ $k | quote }}: {{ $v | quote }}
  {{- end }}
