{{- if .Values.externalSecrets.enabled -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: logger-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
  {{- with .Values.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    {{- with .Values.externalSecrets.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backendType: secretsManager
  data:
  - key: loggerSecret
    name: {{ .Values.externalSecrets.loggerSecretKey }}
  template:
    metadata:
      {{- with .Values.externalSecrets.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "discourse.labels" . | nindent 8 }}
        {{- with .Values.externalSecrets.labels }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
    data:
      log_files.yml: |
        <%= Buffer.from(yaml.dump(JSON.parse(data.loggerSecret))).toString("base64") %>
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: logger-config
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  log_files.yml: |
    files:
      - /logs/rails/*.log
    destination:
      host: logs.papertrailapp.com
      port: 12345
      protocol: tls
{{- end }}
