{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: logger-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
  {{- with .Values.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    {{- with .Values.externalSecrets.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  data:
    - remoteRef:
        key: {{ .Values.externalSecrets.loggerSecretKey }}
      secretKey: loggerSecret
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.store }}
  target:
    name: logger-config
    template:
      metadata:
        {{- with .Values.externalSecrets.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        labels:
          {{- include "discourse.labels" . | nindent 10 }}
          {{- with .Values.externalSecrets.labels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      data:
        log_files.yml: |
          {{ `{{ loggerSecret | fromJson | toYaml }}` }}
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: logger-config
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  log_files.yml: |
    files:
      - /logs/rails/*.log
    destination:
      host: logs.papertrailapp.com
      port: 12345
      protocol: tls
{{- end }}
