{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
  {{- with .Values.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    {{- with .Values.externalSecrets.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  data:
    {{- with .Values.externalSecrets.secrets }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.store }}
  target:
    name: {{ .Values.externalSecrets.target }} 
    template:
      metadata:
        {{- with .Values.externalSecrets.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        labels:
          {{- include "discourse.labels" . | nindent 10 }}
          {{- with .Values.externalSecrets.labels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
