{{- if .Values.externalSecrets.enabled -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
  {{- with .Values.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    {{- with .Values.externalSecrets.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backendType: secretsManager
  data:
    {{- with .Values.externalSecrets.secrets }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.externalSecrets.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "discourse.labels" . | nindent 8 }}
        {{- with .Values.externalSecrets.labels }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
