---
apiVersion: v1
kind: Service
metadata:
  name: discourse
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "discourse.selectorLabels" . | nindent 4 }}
  type: ClusterIP
