{{- if .Values.influxdb.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influx-secret
spec:
  data:
    - remoteRef:
        key: "{{ .Values.influxdb.secret_key }}"
        property: "{{ .Values.influxdb.property }}"
      secretKey: "{{ .Values.influxdb.secret_name }}"
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.store }}
  target:
    name: {{ .Values.influxdb.secret_name }} 
{{- end }}
