apiVersion: v2
name: etherpad
description: A Helm chart for the Mozilla Etherpad application
type: application
version: 1.0.2

keywords:
  - Mozilla
  - etherpad
  - pad

home: https://github.com/mozilla-it/etherpad-docker
sources:
  - https://github.com/mozilla-it/etherpad-docker

maintainers:
  - name: Web SRE Team
    email: it-sre@mozilla.com

dependencies:
- name: cert-manager
  version: 1.8.2
  condition: cert-manager.install
  repository: https://charts.jetstack.io
- name: mysql
  version: 9.2.0
  condition: mysql.install
  repository: https://charts.bitnami.com/bitnami
