apiVersion: v2
name: mozmoderator
description: A Helm Chart for Mozilla's Moderator application
type: application
version: 0.3.0
appVersion: c285426edacb3a1791bab84f64c16d00e6d865eb
keywords:
  - Mozilla
  - moderator
sources:
  - https://github.com/mozilla/mozmoderator
maintainers:
  - name: Web SRE Team
    email: it-sre@mozilla.com

dependencies:
- name: cert-manager
  version: 1.4.4
  condition: cert-manager.install
  repository: https://charts.jetstack.io
- name: mysql
  version: 9.2.0
  condition: mysql.install
  repository: https://charts.bitnami.com/bitnami
