# Default values for careers.
replicaCount: 1

# this is special helm operator magic, image.tag can be kept up to date with the automated image deploys
image:
  repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/careers
  pullPolicy: IfNotPresent
  tag: "stg-91980d9b"

fullnameOverride: "careers"

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: careers.mozilla.org
      paths:
        - path: /
      backend:
        serviceName: careers
        servicePort: 80

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70

configMap:
  allowedHosts: '"*"'

externalSecrets:
  enabled: false
  secretName: ""

imagePullSecrets: []

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations:
  "prometheus.io/scrape": "false"

securityContext: {}
nameOverride: ""
