---
apiVersion: v1
kind: Service
metadata:
  name: moderator
  labels:
    {{- include "mozmoderator.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    {{- include "mozmoderator.selectorLabels" . | nindent 4 }}
  type: ClusterIP
